# Generated by Django 3.0.1 on 2020-03-06 16:18

import ProductPage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=ProductPage.models.IntegerRangeField(default='5'),
        ),
    ]
