# Generated by Django 3.0.3 on 2020-03-06 15:02

from django.db import migrations, models
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='img_url',
            field=models.ImageField(blank=True, null=True, upload_to=homepage.models.get_image_path),
        ),
    ]
