# Generated by Django 3.0.3 on 2020-03-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('code_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('price_cut', models.PositiveSmallIntegerField()),
                ('minimum_price', models.IntegerField()),
                ('expired_date', models.DateField()),
            ],
        ),
    ]
